# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(default='--', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='-', max_length=10)),
                ('unit', models.CharField(default='-', max_length=10)),
                ('unit_price', models.FloatField(default=0)),
                ('no_units', models.FloatField(default=0, verbose_name='number of units')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_ending', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.ItemBase')),
            ],
            bases=('simulation.itembase',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.ItemBase')),
            ],
            bases=('simulation.itembase',),
        ),
        migrations.CreateModel(
            name='Xfer',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.ItemBase')),
            ],
            bases=('simulation.itembase',),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.SimulationYear'),
        ),
        migrations.AddField(
            model_name='xfer',
            name='destination_enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xferin', to='simulation.Enterprise'),
        ),
        migrations.AddField(
            model_name='xfer',
            name='source_enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xferout', to='simulation.Enterprise'),
        ),
        migrations.AddField(
            model_name='income',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Enterprise'),
        ),
        migrations.AddField(
            model_name='cost',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Enterprise'),
        ),
    ]
