# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('overdraft_interest', models.FloatField()),
                ('credit_interest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('termination', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('unit_value', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Enterprises')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Goods')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Accounts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('unit_value', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Accounts')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Goods')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Enterprises')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('unit_value', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xfer_in', to='simulation.Enterprises')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Goods')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xfer_out', to='simulation.Enterprises')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('precipitation', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('mean_vapour_pressure', models.FloatField()),
                ('mean_relative_humidity', models.FloatField()),
                ('sunshine', models.FloatField()),
                ('downward_diffuse_irradiation', models.FloatField()),
                ('direct_irradiation', models.FloatField()),
                ('potential_evapotranspiration', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Units'),
        ),
    ]
