# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fme', models.FloatField()),
                ('erdp', models.FloatField()),
                ('dup', models.FloatField()),
            ],
        ),
    ]
