# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('minInclusion', models.FloatField(null=True)),
                ('maxInclusion', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feeds',
            name='maxInclusion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='me',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='qm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='feed_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simulation.FeedTypes'),
            preserve_default=False,
        ),
    ]
