# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20170719_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulation.Rep'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rep',
            unique_together=set([('scenario', 'number')]),
        ),
    ]
