# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20170720_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=20, unique=True)),
                ('MM', models.FloatField(null=True)),
                ('MML', models.FloatField(null=True)),
                ('BW', models.FloatField(null=True)),
                ('peak_yield', models.FloatField(null=True)),
                ('BW_adjustment_Q1', models.FloatField(null=True)),
                ('BW_adjustment_Q2', models.FloatField(null=True)),
                ('BW_adjustment_Q3', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tradessheet',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
