# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20160825_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='itembase',
            name='item',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='itembase',
            name='unit',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
