# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_auto_20170727_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeddetails',
            name='BW_adjustment_Q4',
            field=models.FloatField(null=True),
        ),
    ]
