# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_breeddetails_bw_adjustment_q4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeds',
            old_name='qm',
            new_name='adf',
        ),
    ]
