# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0009_auto_20170828_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreedDetails',
        ),
    ]
