# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0010_delete_breeddetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeds',
            new_name='Feed',
        ),
        migrations.RenameModel(
            old_name='FeedTypes',
            new_name='FeedType',
        ),
    ]
