# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0012_auto_20170828_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
