# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0013_auto_20170828_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='avaliable',
            field=models.FloatField(null=True),
        ),
    ]
